### ISSUE TITLE
Patroni fails on node2.

### ISSUE THREAD

**Issue by guriandoro** [ihanick/anydbver#21]
In a 3-node PG/Patroni environment, the same node name is being used in nodes 1 and 2, so this is creating conflicts.
I noticed the yaml file is named the same in both nodes, too.

Node1:
```
[root@node1 ~]# head /etc/patroni/cluster1-1.yml
scope: stampede
#namespace: /service/
name: cluster1-1
restapi:
 listen: 0.0.0.0:8008
 connect_address: 192.168.48.3:8008
etcd:
 host: 192.168.48.3:2379
bootstrap:
 # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
```

Node2
```
[root@node2 ~]# head /etc/patroni/cluster1-1.yml
scope: stampede
#namespace: /service/
name: cluster1-1
restapi:
 listen: 0.0.0.0:8008
 connect_address: 192.168.48.4:8008
etcd:
 host: 192.168.48.4:2379
bootstrap:
 # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
```

Everything else but the name is ok (like IP addresses).
