### ISSUE TITLE
k8s-pxc + k8s-minio automatic configuration has some bugs

### ISSUE THREAD

**Issue by leo-bacchi** [ihanick/anydbver#33]
When deploying k8s-pxc and k8s-minio with the command below:
`anydbver deploy k8s-minio k8s-pxc:1.14.0`

We get this configuration automatically:
```
        minio:
          s3:
            bucket: operator-testing
            credentialsSecret: my-cluster-name-backup-s3
            endpointUrl: https://minio-service.default.svc.cluster.local:443
            region: us-east-1
          type: s3
          verifyTLS: false
```

Trying to use it, we get the error:
```
+ echo '+ mc -C /tmp/mc --insecure config host add dest [https://minio-service.default.svc.cluster.local:443](https://minio-service.default.svc.cluster.local/) ACCESS_KEY_ID SECRET_ACCESS_KEY '
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://minio-service.default.svc.cluster.local/probe-bsign-qltvmfr4kpa2czyzgh6bysj2u3hbun/?location=": dial tcp 10.43.135.13:443: i/o timeout.
```

That seems to be because the minio service is deployed on 9000 instead of 443, and it uses HTTP instead of https. 
`minio-service   ClusterIP   10.43.135.13   <none>        9000/TCP,9001/TCP   47m`

Changing `endpointUrl: https://minio-service.default.svc.cluster.local:443` to `endpointUrl: http://minio-service.default.svc.cluster.local:9000` does the trick.
